package java_GUI_Project_PINGPONG;
import java.awt.*;
import java.awt.event.*;
import java.util.*;
import javax.swing.*;
/* The Rectangle class specifies an area in 
 * a coordinate space that is enclosed by 
 * the Rectangle object's upper-left 
 * point (x,y) in the coordinate space, 
 * its width, and its height
 */
public class Ball extends Rectangle{
	//properties, private access specifier
	private Random random;    //the random generator
	int         XVelocity,    //the horizontal velocity of the ping pong ball
	            YVelocity,    //the vertical velocity of the ping pong ball
	            InitailSpeed=2; //The Initial speed of the ball
	
	
	//public access specifier
	public Ball(int x,int y, int width,int height)
	{
		//Since Rectangle is a super class of Ball, use super to assign
		//these arguments for us
		super(x,y,width,height);
		//Set a random direction in which this ball goes in
		
		//Finish initializing Random
		random = new Random();
		//Create a local variable for the ball constructor
		int randomXDirection = random.nextInt(2); //0 or 1, if it is 0 ball go left, 1 ball go right
		if(randomXDirection==0)
		{
			//Have the Ball go left
			
			//Decrement 1 from randomXDirection so hence it becomes -1
			randomXDirection--;	
		}
		//call setXDirection and pass randomxDirection
		this.setXDirection(randomXDirection*this.InitailSpeed);
		
		int randomYDirection = random.nextInt(2); //0 or 1, if it is 0 ball go left, 1 ball go right
		if(randomYDirection==0)
		{
			//Have the Ball go left
			//Decrement 1 from randomYDirection so hence it becomes -1
			randomYDirection--;	
		}
		//call setYDirection and pass randomYDirection
		this.setYDirection(randomYDirection*this.InitailSpeed);
		
		
	}
	
	//When we create a new ball, its going to go in a 
	//random direction so the instance of random class
	//will take care of the Randomness
	public void setXDirection(int RandomXDirection)
	{
		//Assign XVelocity the RandomXDirection generated by constructor
		this.XVelocity = RandomXDirection;
	}
	
	public void setYDirection(int RandomYDirection)
	{
		//Assign YVelocity the RandomYDirection
		this.YVelocity = RandomYDirection;
	}
	
	public void move()
	{
		//Add the XVelocity value to your ball's x location
		this.x+=this.XVelocity;
		//Add the YVelocity value to your ball's y location
		this.y+=this.YVelocity;
	}
	
	public void draw(Graphics g)
	{
		//Set the color of ball
		g.setColor(new Color(224,100,0));
		//Fill the Oval or Circle
		g.fillOval(this.x,this.y,this.height,this.width);
	}
	
	//Return the Xvelicity
	public int GetXVelocity()
	{
		return this.XVelocity;
	}
	
	//Return the YVelocity
	public int GetYVelocity()
	{
		return this.YVelocity;
	}

}
